# Generate Selenium IDE project file for manually running all tests.

# USAGE: python3 side-project.py

import json

from pathlib import Path

from decouple import config

project_wrapper = {
    "id": "b5ca31b1-18e3-4f09-bb46-58911b663ebc",
    "version": "2.0",
    "name": "libguine",
    "url": "https://caltech.libapps.com",
    "tests": [],
    "suites": [],
    "urls": ["https://caltech.libapps.com/"],
    "plugins": [],
}

login = {
    "id": "9bd153bb-6f15-4205-b4a9-324a7c04a2d7",
    "name": "login",
    "commands": [
        {
            "id": "2fbca67d-c362-476e-991a-1466bf16640e",
            "comment": "",
            "command": "open",
            "target": "/libapps/login.php",
            "targets": [],
            "value": "",
        },
        {
            "id": "71a48c21-f2ba-461f-91c6-54bc797de726",
            "comment": "",
            "command": "setWindowSize",
            "target": "1280x800",
            "targets": [],
            "value": "",
        },
        {
            "id": "c70c0af0-88a0-4ef5-9a97-6b87619587e0",
            "comment": "",
            "command": "storeXpathCount",
            "target": "xpath=//input[@id='s-libapps-email']",
            "targets": [],
            "value": "login",
        },
        {
            "id": "6caaee83-7dba-4986-856c-c97bbb2ced51",
            "comment": "",
            "command": "if",
            "target": "${login}>0",
            "targets": [],
            "value": "",
        },
        {
            "id": "4b893d45-a7bb-4ef1-a588-9ae1f84db5b4",
            "comment": "",
            "command": "click",
            "target": "id=s-libapps-email",
            "targets": [
                ["id=s-libapps-email", "id"],
                ["name=s-libapps-email", "name"],
                ["css=#s-libapps-email", "css:finder"],
                ["xpath=//input[@id='s-libapps-email']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[2]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[2]/input", "xpath:position"],
            ],
            "value": "",
        },
        {
            "id": "dc90b480-3677-4e18-82a9-16f13e5c46f2",
            "comment": "",
            "command": "type",
            "target": "id=s-libapps-email",
            "targets": [
                ["id=s-libapps-email", "id"],
                ["name=s-libapps-email", "name"],
                ["css=#s-libapps-email", "css:finder"],
                ["xpath=//input[@id='s-libapps-email']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[2]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[2]/input", "xpath:position"],
            ],
            "value": config("LIBAPPS_USER"),
        },
        {
            "id": "b7f40917-6d9a-4bf8-b861-bade6ff6bf85",
            "comment": "",
            "command": "type",
            "target": "id=s-libapps-password",
            "targets": [
                ["id=s-libapps-password", "id"],
                ["name=s-libapps-password", "name"],
                ["css=#s-libapps-password", "css:finder"],
                ["xpath=//input[@id='s-libapps-password']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[3]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[3]/input", "xpath:position"],
            ],
            "value": config("LIBAPPS_PASS"),
        },
        {
            "id": "b93c62fb-3ac4-4e76-b3c0-ae7b4bed28a5",
            "comment": "",
            "command": "click",
            "target": "id=s-libapps-login-button",
            "targets": [
                ["id=s-libapps-login-button", "id"],
                ["css=#s-libapps-login-button", "css:finder"],
                ["xpath=//button[@id='s-libapps-login-button']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[4]/button",
                    "xpath:idRelative",
                ],
                ["xpath=//button", "xpath:position"],
                ["xpath=//button[contains(.,'Log Into LibApps')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "45da2869-efa6-45d5-95b2-4f4e62156c43",
            "comment": "",
            "command": "end",
            "target": "",
            "targets": [],
            "value": "",
        },
        {
            "id": "2a5fa54d-11c8-4a0e-9319-2cd5faa76f48",
            "comment": "",
            "command": "click",
            "target": "id=s-lib-app-anchor",
            "targets": [
                ["id=s-lib-app-anchor", "id"],
                ["linkText=LibApps", "linkText"],
                ["css=#s-lib-app-anchor", "css:finder"],
                ["xpath=//a[contains(text(),'LibApps')]", "xpath:link"],
                ["xpath=//a[@id='s-lib-app-anchor']", "xpath:attributes"],
                [
                    "xpath=//nav[@id='s-lg-admin-command-bar']/div/ul/li/a",
                    "xpath:idRelative",
                ],
                ["xpath=//a[contains(@href, '#')]", "xpath:href"],
                ["xpath=//a", "xpath:position"],
                ["xpath=//a[contains(.,'LibApps ')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "ace1b57e-d7d3-488d-ac55-d9ca78367ff9",
            "comment": "",
            "command": "click",
            "target": "linkText=LibGuides",
            "targets": [
                ["linkText=LibGuides", "linkText"],
                ["css=li:nth-child(3) > .dropdown-item", "css:finder"],
                ["xpath=//a[contains(text(),'LibGuides')]", "xpath:link"],
                ["xpath=//ul[@id='s-lib-app-menu']/li[3]/a", "xpath:idRelative"],
                [
                    "xpath=//a[contains(@href, 'https://caltech.libapps.com/libapps/login.php?site_id=64')]",
                    "xpath:href",
                ],
                ["xpath=//li[3]/a", "xpath:position"],
                ["xpath=//a[contains(.,'LibGuides')]", "xpath:innerText"],
            ],
            "value": "",
        },
    ],
}
project_wrapper["tests"].append(login)

# template-home--archives
with open("template-home--archives.html") as f:
    html_template_home__archives = f.read()

template_home__archives = {
    "id": "168b9449-3cca-4af8-9776-b765e9056d90",
    "name": "template-home--archives",
    "commands": [
        {
            "id": "6183717d-6a4a-4018-9535-9dce93545eb8",
            "comment": "",
            "command": "open",
            "target": "/libapps/login.php",
            "targets": [],
            "value": "",
        },
        {
            "id": "6f795906-68b9-475e-87de-a89005302091",
            "comment": "",
            "command": "setWindowSize",
            "target": "1280x800",
            "targets": [],
            "value": "",
        },
        {
            "id": "37baac27-5af8-4330-9ae8-1c41973de2fe",
            "comment": "",
            "command": "storeXpathCount",
            "target": "xpath=//input[@id='s-libapps-email']",
            "targets": [],
            "value": "login",
        },
        {
            "id": "9f2a3acd-8a80-4764-9585-25922a30e9ef",
            "comment": "",
            "command": "if",
            "target": "${login}>0",
            "targets": [],
            "value": "",
        },
        {
            "id": "6cea14ef-df67-4852-8913-625f1ee779f7",
            "comment": "",
            "command": "click",
            "target": "id=s-libapps-email",
            "targets": [
                ["id=s-libapps-email", "id"],
                ["name=s-libapps-email", "name"],
                ["css=#s-libapps-email", "css:finder"],
                ["xpath=//input[@id='s-libapps-email']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[2]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[2]/input", "xpath:position"],
            ],
            "value": "",
        },
        {
            "id": "a64bfc1b-e396-4fdf-8f55-83e0bcc08c30",
            "comment": "",
            "command": "type",
            "target": "id=s-libapps-email",
            "targets": [
                ["id=s-libapps-email", "id"],
                ["name=s-libapps-email", "name"],
                ["css=#s-libapps-email", "css:finder"],
                ["xpath=//input[@id='s-libapps-email']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[2]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[2]/input", "xpath:position"],
            ],
            "value": config("LIBAPPS_USER"),
        },
        {
            "id": "deed805b-5808-452a-a87e-f4e118f499ad",
            "comment": "",
            "command": "type",
            "target": "id=s-libapps-password",
            "targets": [
                ["id=s-libapps-password", "id"],
                ["name=s-libapps-password", "name"],
                ["css=#s-libapps-password", "css:finder"],
                ["xpath=//input[@id='s-libapps-password']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[3]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[3]/input", "xpath:position"],
            ],
            "value": config("LIBAPPS_PASS"),
        },
        {
            "id": "53d95877-b604-4329-80e5-f053669ab61d",
            "comment": "",
            "command": "click",
            "target": "id=s-libapps-login-button",
            "targets": [
                ["id=s-libapps-login-button", "id"],
                ["css=#s-libapps-login-button", "css:finder"],
                ["xpath=//button[@id='s-libapps-login-button']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[4]/button",
                    "xpath:idRelative",
                ],
                ["xpath=//button", "xpath:position"],
                ["xpath=//button[contains(.,'Log Into LibApps')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "03620724-19c8-4790-958c-f006f46c4f02",
            "comment": "",
            "command": "end",
            "target": "",
            "targets": [],
            "value": "",
        },
        {
            "id": "e11308dc-adee-4c14-9c5a-4bc5440c49f6",
            "comment": "",
            "command": "click",
            "target": "id=s-lib-app-anchor",
            "targets": [
                ["id=s-lib-app-anchor", "id"],
                ["linkText=LibApps", "linkText"],
                ["css=#s-lib-app-anchor", "css:finder"],
                ["xpath=//a[contains(text(),'LibApps')]", "xpath:link"],
                ["xpath=//a[@id='s-lib-app-anchor']", "xpath:attributes"],
                [
                    "xpath=//nav[@id='s-lg-admin-command-bar']/div/ul/li/a",
                    "xpath:idRelative",
                ],
                ["xpath=//a[contains(@href, '#')]", "xpath:href"],
                ["xpath=//a", "xpath:position"],
                ["xpath=//a[contains(.,'LibApps ')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "8cdb5f8c-5153-4beb-92bc-4f05afda2dc0",
            "comment": "",
            "command": "click",
            "target": "linkText=LibGuides",
            "targets": [
                ["linkText=LibGuides", "linkText"],
                ["css=li:nth-child(3) > .dropdown-item", "css:finder"],
                ["xpath=//a[contains(text(),'LibGuides')]", "xpath:link"],
                ["xpath=//ul[@id='s-lib-app-menu']/li[3]/a", "xpath:idRelative"],
                [
                    "xpath=//a[contains(@href, 'https://caltech.libapps.com/libapps/login.php?site_id=64')]",
                    "xpath:href",
                ],
                ["xpath=//li[3]/a", "xpath:position"],
                ["xpath=//a[contains(.,'LibGuides')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "f6ec2a38-8b4d-480d-af60-32cb6e41df14",
            "comment": "",
            "command": "click",
            "target": "linkText=Admin",
            "targets": [
                ["linkText=Admin", "linkText"],
                ["css=.dropdown:nth-child(11) > a", "css:finder"],
                [
                    "xpath=//nav[@id='s-lg-admin-command-bar']/ul/li[11]/a",
                    "xpath:idRelative",
                ],
                ["xpath=(//a[contains(@href, '#')])[5]", "xpath:href"],
                ["xpath=//nav/ul/li[11]/a", "xpath:position"],
                ["xpath=//a[contains(.,'Admin')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "35f4e7db-78b4-46cf-8472-57afae2376ee",
            "comment": "",
            "command": "click",
            "target": "linkText=Look & Feel",
            "targets": [
                ["linkText=Look & Feel", "linkText"],
                ["css=.open li:nth-child(2) > a", "css:finder"],
                ["xpath=//a[contains(text(),'Look & Feel')]", "xpath:link"],
                ["xpath=(//a[@onclick=''])[17]", "xpath:attributes"],
                [
                    "xpath=//nav[@id='s-lg-admin-command-bar']/ul/li[11]/ul/li[2]/a",
                    "xpath:idRelative",
                ],
                ["xpath=//a[contains(@href, 'lookfeel.php')]", "xpath:href"],
                ["xpath=//li[11]/ul/li[2]/a", "xpath:position"],
                ["xpath=//a[contains(.,'Look & Feel')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "4455637e-da8a-4087-b28e-cc2d534d6719",
            "comment": "",
            "command": "click",
            "target": "linkText=Page Layout",
            "targets": [
                ["linkText=Page Layout", "linkText"],
                ["css=li:nth-child(3) > .dropdown-toggle", "css:finder"],
                ["xpath=//a[contains(text(),'Page Layout')]", "xpath:link"],
                ["xpath=//div[@id='col1']/ul/li[3]/a", "xpath:idRelative"],
                ["xpath=(//a[contains(@href, '#')])[6]", "xpath:href"],
                ["xpath=//div/ul/li[3]/a", "xpath:position"],
                ["xpath=//a[contains(.,'Page Layout ')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "7fcb3b41-b4c5-4625-8b72-dc298b88085e",
            "comment": "",
            "command": "click",
            "target": "linkText=Guide",
            "targets": [
                ["linkText=Guide", "linkText"],
                ["css=.open li:nth-child(1) > a", "css:finder"],
                ["xpath=(//a[contains(text(),'Guide')])[5]", "xpath:link"],
                ["xpath=//div[@id='col1']/ul/li[3]/ul/li/a", "xpath:idRelative"],
                ["xpath=//a[contains(@href, '?action=3')]", "xpath:href"],
                ["xpath=//div/ul/li[3]/ul/li/a", "xpath:position"],
            ],
            "value": "",
        },
        {
            "id": "7f5e1f70-19ac-46fc-96cc-9d182f49f687",
            "comment": "",
            "command": "click",
            "target": "id=s-lg-guide-templates_link",
            "targets": [
                [
                    "css=#s-lg-guide-templates_link > .s-lg-admin-field-label",
                    "css:finder",
                ],
                ["xpath=//a[@id='s-lg-guide-templates_link']/span", "xpath:idRelative"],
                ["xpath=//div[2]/div/a/span", "xpath:position"],
                [
                    "xpath=//span[contains(.,'Customize Guide Templates')]",
                    "xpath:innerText",
                ],
            ],
            "value": "",
        },
        {
            "id": "6aab83df-a835-488b-a8f3-5bbcabb1939d",
            "comment": "",
            "command": "mouseDown",
            "target": "id=select2-chosen-2",
            "targets": [
                ["id=select2-chosen-2", "id"],
                ["css=#select2-chosen-2", "css:finder"],
                ["xpath=//span[@id='select2-chosen-2']", "xpath:attributes"],
                [
                    "xpath=//div[@id='s2id_guide-template-id']/a/span",
                    "xpath:idRelative",
                ],
                ["xpath=//td/div/a/span", "xpath:position"],
                ["xpath=//span[contains(.,'Select a template...')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "c6296a5f-977b-4718-b3ee-1a57a45807c8",
            "comment": "",
            "command": "mouseUp",
            "target": "id=select2-drop-mask",
            "targets": [
                ["id=select2-drop-mask", "id"],
                ["css=#select2-drop-mask", "css:finder"],
                ["xpath=//div[@id='select2-drop-mask']", "xpath:attributes"],
                ["xpath=//div[7]", "xpath:position"],
            ],
            "value": "",
        },
        {
            "id": "9c65fc90-ecf7-46a0-8116-3b3f49885940",
            "comment": "",
            "command": "type",
            "target": "id=s2id_autogen2_search",
            "targets": [
                ["id=s2id_autogen2_search", "id"],
                ["css=#s2id_autogen2_search", "css:finder"],
                ["xpath=//input[@id='s2id_autogen2_search']", "xpath:attributes"],
                ["xpath=//div[@id='select2-drop']/div/input", "xpath:idRelative"],
                ["xpath=//div[8]/div/input", "xpath:position"],
            ],
            "value": "template-home--archives",
        },
        {
            "id": "2d8f524a-1465-441f-b86a-49d09409f001",
            "comment": "",
            "command": "sendKeys",
            "target": "id=s2id_autogen2_search",
            "targets": [
                ["id=s2id_autogen2_search", "id"],
                ["css=#s2id_autogen2_search", "css:finder"],
                ["xpath=//input[@id='s2id_autogen2_search']", "xpath:attributes"],
                ["xpath=//div[@id='select2-drop']/div/input", "xpath:idRelative"],
                ["xpath=//div[8]/div/input", "xpath:position"],
            ],
            "value": "${KEY_ENTER}",
        },
        {
            "id": "43fc6573-1278-46e3-959a-361891843088",
            "comment": "",
            "command": "click",
            "target": "id=template_code",
            "targets": [
                ["id=template_code", "id"],
                ["name=template_code", "name"],
                ["css=#template_code", "css:finder"],
                ["xpath=//textarea[@id='template_code']", "xpath:attributes"],
                [
                    "xpath=//div[@id='template_code_container']/textarea",
                    "xpath:idRelative",
                ],
                ["xpath=//textarea", "xpath:position"],
            ],
            "value": "",
        },
        {
            "id": "28d9e53e-c336-497c-8c43-ea41fb748f8e",
            "comment": "",
            "command": "type",
            "target": "id=template_code",
            "targets": [
                ["id=template_code", "id"],
                ["name=template_code", "name"],
                ["css=#template_code", "css:finder"],
                ["xpath=//textarea[@id='template_code']", "xpath:attributes"],
                [
                    "xpath=//div[@id='template_code_container']/textarea",
                    "xpath:idRelative",
                ],
                ["xpath=//textarea", "xpath:position"],
            ],
            "value": html_template_home__archives,
        },
        {
            "id": "b6fc2c77-8ff0-4609-81d7-d7ffa5b99977",
            "comment": "",
            "command": "click",
            "target": "id=btn-save-template",
            "targets": [
                ["id=btn-save-template", "id"],
                ["css=#btn-save-template", "css:finder"],
                ["xpath=//button[@id='btn-save-template']", "xpath:attributes"],
                [
                    "xpath=//form[@id='frm-guide-template-code']/table/tbody/tr[2]/td/div[6]/button",
                    "xpath:idRelative",
                ],
                ["xpath=//div[6]/button", "xpath:position"],
                [
                    "xpath=//button[contains(.,'Save changes to this template')]",
                    "xpath:innerText",
                ],
            ],
            "value": "",
        },
    ],
}
project_wrapper["tests"].append(template_home__archives)

# upload-css--custom
slug = "upload-css--custom"
filepath = str(Path("assets/custom.css").resolve())

upload_css__custom = {
    "id": "71c7a101-ecf6-42dc-a56e-7ff002076244",
    "name": slug,
    "commands": [
        {
            "id": "a11b0406-0302-4190-a2e8-bb6c35dc166b",
            "comment": "",
            "command": "open",
            "target": "/libapps/login.php",
            "targets": [],
            "value": "",
        },
        {
            "id": "17aaabc0-7587-4058-bf20-20cf862bc41e",
            "comment": "",
            "command": "setWindowSize",
            "target": "1280x800",
            "targets": [],
            "value": "",
        },
        {
            "id": "7bdd28a4-c07d-4bb8-a53e-c346277f9542",
            "comment": "",
            "command": "storeXpathCount",
            "target": "xpath=//input[@id='s-libapps-email']",
            "targets": [],
            "value": "login",
        },
        {
            "id": "4f890956-a08f-4003-be4b-b1dd3e2116a3",
            "comment": "",
            "command": "if",
            "target": "${login}>0",
            "targets": [],
            "value": "",
        },
        {
            "id": "5b7498fc-c86e-4301-ae3c-5995be9df39a",
            "comment": "",
            "command": "click",
            "target": "id=s-libapps-email",
            "targets": [
                ["id=s-libapps-email", "id"],
                ["name=s-libapps-email", "name"],
                ["css=#s-libapps-email", "css:finder"],
                ["xpath=//input[@id='s-libapps-email']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[2]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[2]/input", "xpath:position"],
            ],
            "value": "",
        },
        {
            "id": "37dd3f4e-37e1-4a9d-b7f8-8e4fbffe07d2",
            "comment": "",
            "command": "type",
            "target": "id=s-libapps-email",
            "targets": [
                ["id=s-libapps-email", "id"],
                ["name=s-libapps-email", "name"],
                ["css=#s-libapps-email", "css:finder"],
                ["xpath=//input[@id='s-libapps-email']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[2]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[2]/input", "xpath:position"],
            ],
            "value": config("LIBAPPS_USER"),
        },
        {
            "id": "2500ccc5-ea45-4726-bc95-18da97b2e639",
            "comment": "",
            "command": "type",
            "target": "id=s-libapps-password",
            "targets": [
                ["id=s-libapps-password", "id"],
                ["name=s-libapps-password", "name"],
                ["css=#s-libapps-password", "css:finder"],
                ["xpath=//input[@id='s-libapps-password']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[3]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[3]/input", "xpath:position"],
            ],
            "value": config("LIBAPPS_PASS"),
        },
        {
            "id": "1ade3120-9591-4a8d-a6de-4cb0bf30986a",
            "comment": "",
            "command": "click",
            "target": "id=s-libapps-login-button",
            "targets": [
                ["id=s-libapps-login-button", "id"],
                ["css=#s-libapps-login-button", "css:finder"],
                ["xpath=//button[@id='s-libapps-login-button']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[4]/button",
                    "xpath:idRelative",
                ],
                ["xpath=//button", "xpath:position"],
                ["xpath=//button[contains(.,'Log Into LibApps')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "43daca78-0cb9-48c7-8517-56910c6fdd32",
            "comment": "",
            "command": "end",
            "target": "",
            "targets": [],
            "value": "",
        },
        {
            "id": "873a7bae-d867-408e-a22e-9c6323fe9d64",
            "comment": "",
            "command": "click",
            "target": "id=s-lib-app-anchor",
            "targets": [
                ["id=s-lib-app-anchor", "id"],
                ["linkText=LibApps", "linkText"],
                ["css=#s-lib-app-anchor", "css:finder"],
                ["xpath=//a[contains(text(),'LibApps')]", "xpath:link"],
                ["xpath=//a[@id='s-lib-app-anchor']", "xpath:attributes"],
                [
                    "xpath=//nav[@id='s-lg-admin-command-bar']/div/ul/li/a",
                    "xpath:idRelative",
                ],
                ["xpath=//a[contains(@href, '#')]", "xpath:href"],
                ["xpath=//a", "xpath:position"],
                ["xpath=//a[contains(.,'LibApps ')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "5bdaa4b6-218c-40c6-942c-40c066c4faa8",
            "comment": "",
            "command": "click",
            "target": "linkText=LibGuides",
            "targets": [
                ["linkText=LibGuides", "linkText"],
                ["css=li:nth-child(3) > .dropdown-item", "css:finder"],
                ["xpath=//a[contains(text(),'LibGuides')]", "xpath:link"],
                ["xpath=//ul[@id='s-lib-app-menu']/li[3]/a", "xpath:idRelative"],
                [
                    "xpath=//a[contains(@href, 'https://caltech.libapps.com/libapps/login.php?site_id=64')]",
                    "xpath:href",
                ],
                ["xpath=//li[3]/a", "xpath:position"],
                ["xpath=//a[contains(.,'LibGuides')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "1defc037-f605-4503-a9cf-5f44740a9ee1",
            "comment": "",
            "command": "click",
            "target": "linkText=Admin",
            "targets": [
                ["linkText=Admin", "linkText"],
                ["css=.dropdown:nth-child(11) > a", "css:finder"],
                [
                    "xpath=//nav[@id='s-lg-admin-command-bar']/ul/li[11]/a",
                    "xpath:idRelative",
                ],
                ["xpath=(//a[contains(@href, '#')])[5]", "xpath:href"],
                ["xpath=//nav/ul/li[11]/a", "xpath:position"],
                ["xpath=//a[contains(.,'Admin')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "5a65f9c9-bd38-48d5-bf87-6abfad5bd9d3",
            "comment": "",
            "command": "click",
            "target": "linkText=Look & Feel",
            "targets": [
                ["linkText=Look & Feel", "linkText"],
                ["css=.open li:nth-child(2) > a", "css:finder"],
                ["xpath=//a[contains(text(),'Look & Feel')]", "xpath:link"],
                ["xpath=(//a[@onclick=''])[17]", "xpath:attributes"],
                [
                    "xpath=//nav[@id='s-lg-admin-command-bar']/ul/li[11]/ul/li[2]/a",
                    "xpath:idRelative",
                ],
                ["xpath=//a[contains(@href, 'lookfeel.php')]", "xpath:href"],
                ["xpath=//li[11]/ul/li[2]/a", "xpath:position"],
                ["xpath=//a[contains(.,'Look & Feel')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "b38478e0-e5e0-4e33-b661-9c782d9040b1",
            "comment": "",
            "command": "click",
            "target": "linkText=Custom JS/CSS",
            "targets": [
                ["linkText=Custom JS/CSS", "linkText"],
                ["css=.nav > li:nth-child(2) > a", "css:finder"],
                ["xpath=//a[contains(text(),'Custom JS/CSS')]", "xpath:link"],
                ["xpath=//div[@id='col1']/ul/li[2]/a", "xpath:idRelative"],
                ["xpath=//a[contains(@href, '?action=1')]", "xpath:href"],
                ["xpath=//div/ul/li[2]/a", "xpath:position"],
                ["xpath=//a[contains(.,'Custom JS/CSS')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "5d730e36-9b95-4646-95bf-793ff2d6ecf1",
            "comment": "",
            "command": "click",
            "target": "css=#s-lg-include-files_link",
            "targets": [
                [
                    "css=#s-lg-include-files_link > .s-lg-admin-field-label",
                    "css:finder",
                ],
                ["xpath=//a[@id='s-lg-include-files_link']/span", "xpath:idRelative"],
                ["xpath=//div[2]/div/a/span", "xpath:position"],
                [
                    "xpath=//span[contains(.,'Upload Customization Files')]",
                    "xpath:innerText",
                ],
            ],
            "value": "",
        },
        {
            "id": "7dfba71e-6e50-47a9-b06e-a62c1c387921",
            "comment": "",
            "command": "type",
            "target": "id=include_file",
            "targets": [
                ["id=include_file", "id"],
                ["name=include_file", "name"],
                ["css=#include_file", "css:finder"],
                ["xpath=//input[@id='include_file']", "xpath:attributes"],
                ["xpath=//div[@id='include_file-grp']/span/input", "xpath:idRelative"],
                ["xpath=//span/input", "xpath:position"],
            ],
            "value": filepath,
        },
    ],
}
project_wrapper["tests"].append(upload_css__custom)

# header--archives
with open("assets/header--archives.html") as f:
    html_header__archives = f.read()

header__archives = {
    "id": "df178b23-6456-4308-b7fa-eb43bf417400",
    "name": "header--archives",
    "commands": [
        {
            "id": "acb526e4-d195-4a21-a729-e984e89e34cd",
            "comment": "",
            "command": "open",
            "target": "/libapps/login.php",
            "targets": [],
            "value": "",
        },
        {
            "id": "95fe314d-aa82-4081-a6c5-d83c23ba8a9d",
            "comment": "",
            "command": "setWindowSize",
            "target": "1280x800",
            "targets": [],
            "value": "",
        },
        {
            "id": "b34553f7-24ef-44d5-868c-66e34fdb3e05",
            "comment": "",
            "command": "storeXpathCount",
            "target": "xpath=//input[@id='s-libapps-email']",
            "targets": [],
            "value": "login",
        },
        {
            "id": "e93ce770-fb79-45d9-89d7-522e4441a292",
            "comment": "",
            "command": "if",
            "target": "${login}>0",
            "targets": [],
            "value": "",
        },
        {
            "id": "3f5841db-c83b-40a9-a201-74bd31d2d274",
            "comment": "",
            "command": "click",
            "target": "id=s-libapps-email",
            "targets": [
                ["id=s-libapps-email", "id"],
                ["name=s-libapps-email", "name"],
                ["css=#s-libapps-email", "css:finder"],
                ["xpath=//input[@id='s-libapps-email']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[2]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[2]/input", "xpath:position"],
            ],
            "value": "",
        },
        {
            "id": "4bc988ed-084f-4791-93ec-19bedbdc55d3",
            "comment": "",
            "command": "type",
            "target": "id=s-libapps-email",
            "targets": [
                ["id=s-libapps-email", "id"],
                ["name=s-libapps-email", "name"],
                ["css=#s-libapps-email", "css:finder"],
                ["xpath=//input[@id='s-libapps-email']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[2]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[2]/input", "xpath:position"],
            ],
            "value": config("LIBAPPS_USER"),
        },
        {
            "id": "b4358e56-2594-4f51-b7a7-74bee3f0dfa8",
            "comment": "",
            "command": "type",
            "target": "id=s-libapps-password",
            "targets": [
                ["id=s-libapps-password", "id"],
                ["name=s-libapps-password", "name"],
                ["css=#s-libapps-password", "css:finder"],
                ["xpath=//input[@id='s-libapps-password']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[3]/input",
                    "xpath:idRelative",
                ],
                ["xpath=//div[3]/input", "xpath:position"],
            ],
            "value": config("LIBAPPS_PASS"),
        },
        {
            "id": "325bc4ad-f902-47b5-8d06-61d6fbf82d45",
            "comment": "",
            "command": "click",
            "target": "id=s-libapps-login-button",
            "targets": [
                ["id=s-libapps-login-button", "id"],
                ["css=#s-libapps-login-button", "css:finder"],
                ["xpath=//button[@id='s-libapps-login-button']", "xpath:attributes"],
                [
                    "xpath=//form[@id='s-libapps-login-form']/div[4]/button",
                    "xpath:idRelative",
                ],
                ["xpath=//button", "xpath:position"],
                ["xpath=//button[contains(.,'Log Into LibApps')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "81ef3f0a-5fdc-44d7-94b3-323a6ed7974d",
            "comment": "",
            "command": "end",
            "target": "",
            "targets": [],
            "value": "",
        },
        {
            "id": "9b2ec152-aae8-41ca-9410-ab8a9a758c77",
            "comment": "",
            "command": "click",
            "target": "id=s-lib-app-anchor",
            "targets": [
                ["id=s-lib-app-anchor", "id"],
                ["linkText=LibApps", "linkText"],
                ["css=#s-lib-app-anchor", "css:finder"],
                ["xpath=//a[contains(text(),'LibApps')]", "xpath:link"],
                ["xpath=//a[@id='s-lib-app-anchor']", "xpath:attributes"],
                [
                    "xpath=//nav[@id='s-lg-admin-command-bar']/div/ul/li/a",
                    "xpath:idRelative",
                ],
                ["xpath=//a[contains(@href, '#')]", "xpath:href"],
                ["xpath=//a", "xpath:position"],
                ["xpath=//a[contains(.,'LibApps ')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "0d62ba2b-297c-4430-9665-0acaf6b2abf4",
            "comment": "",
            "command": "click",
            "target": "linkText=LibGuides",
            "targets": [
                ["linkText=LibGuides", "linkText"],
                ["css=li:nth-child(3) > .dropdown-item", "css:finder"],
                ["xpath=//a[contains(text(),'LibGuides')]", "xpath:link"],
                ["xpath=//ul[@id='s-lib-app-menu']/li[3]/a", "xpath:idRelative"],
                [
                    "xpath=//a[contains(@href, 'https://caltech.libapps.com/libapps/login.php?site_id=64')]",
                    "xpath:href",
                ],
                ["xpath=//li[3]/a", "xpath:position"],
                ["xpath=//a[contains(.,'LibGuides')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "1b1e3d45-9e3d-4d21-bd6c-f486d5a890e6",
            "comment": "",
            "command": "click",
            "target": "linkText=Admin",
            "targets": [
                ["linkText=Admin", "linkText"],
                ["css=.dropdown:nth-child(11) > a", "css:finder"],
                [
                    "xpath=//nav[@id='s-lg-admin-command-bar']/ul/li[11]/a",
                    "xpath:idRelative",
                ],
                ["xpath=(//a[contains(@href, '#')])[5]", "xpath:href"],
                ["xpath=//nav/ul/li[11]/a", "xpath:position"],
                ["xpath=//a[contains(.,'Admin')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "a53bed87-390d-432f-86a8-7747b7e62661",
            "comment": "",
            "command": "click",
            "target": "linkText=Groups",
            "targets": [
                ["linkText=Groups", "linkText"],
                ["css=.open li:nth-child(4) > a", "css:finder"],
                ["xpath=//a[contains(text(),'Groups')]", "xpath:link"],
                ["xpath=(//a[@onclick=''])[19]", "xpath:attributes"],
                [
                    "xpath=//nav[@id='s-lg-admin-command-bar']/ul/li[11]/ul/li[4]/a",
                    "xpath:idRelative",
                ],
                ["xpath=//a[contains(@href, 'groups.php')]", "xpath:href"],
                ["xpath=//li[11]/ul/li[4]/a", "xpath:position"],
                ["xpath=//a[contains(.,'Groups')]", "xpath:innerText"],
            ],
            "value": "",
        },
        {
            "id": "af4df3ae-7ef8-4d30-9fd7-0f62dace1c21",
            "comment": "click edit icon for Archives Group",
            "command": "click",
            "target": "css=#s-lg-admin-datatable-row-346-27077 .fa-edit",
            "targets": [
                ["css=#s-lg-admin-datatable-row-346-27077 .fa-edit", "css:finder"],
                [
                    "xpath=//tr[@id='s-lg-admin-datatable-row-346-27077']/td[6]/div/a/i",
                    "xpath:idRelative",
                ],
                ["xpath=//div/a/i", "xpath:position"],
            ],
            "value": "",
        },
        {
            "id": "28442e67-fdea-4527-948b-63cf24f1afea",
            "comment": "",
            "command": "click",
            "target": "linkText=Header / Footer / Tabs / Boxes",
            "targets": [
                ["linkText=Header / Footer / Tabs / Boxes", "linkText"],
                ["css=.nav-tabs > li:nth-child(3) > a", "css:finder"],
                [
                    "xpath=//a[contains(text(),'Header / Footer / Tabs / Boxes')]",
                    "xpath:link",
                ],
                ["xpath=//div[@id='col1']/ul/li[3]/a", "xpath:idRelative"],
                [
                    "xpath=//a[contains(@href, '?action=2&group_id=27077')]",
                    "xpath:href",
                ],
                ["xpath=//div/ul/li[3]/a", "xpath:position"],
                [
                    "xpath=//a[contains(.,'Header / Footer / Tabs / Boxes')]",
                    "xpath:innerText",
                ],
            ],
            "value": "",
        },
        {
            "id": "82e4a540-1888-4ce9-85b6-2a85723f17e4",
            "comment": "",
            "command": "type",
            "target": "id=banner_html",
            "targets": [
                ["id=banner_html", "id"],
                ["name=banner_html", "name"],
                ["css=#banner_html", "css:finder"],
                ["xpath=//textarea[@id='banner_html']", "xpath:attributes"],
                [
                    "xpath=//div[@id='s-lg-banners']/div/table/tbody/tr/td/div[3]/textarea",
                    "xpath:idRelative",
                ],
                ["xpath=//textarea", "xpath:position"],
            ],
            "value": html_header__archives,
        },
        {
            "id": "fecb8da2-d1ba-44d3-8a53-0057130090e7",
            "comment": "press Save HTML button",
            "command": "click",
            "target": "css=#banner_html + button",
            "targets": [
                ["css=.margin-top-sm", "css:finder"],
                [
                    "xpath=//button[@onclick=\"springSpace.adminObj.saveSitePropTextarea({\n                                                    processing_script: 'lookfeel_process.php',\n                                                    elt: document.getElementById('banner_html'),\n                                                    action: 79,\n                                                    is_meta: 1,\n                                                    group_id: 27077,\n                                                    button: this\n                                                });\"]",
                    "xpath:attributes",
                ],
                [
                    "xpath=//div[@id='s-lg-banners']/div/table/tbody/tr/td/div[3]/button",
                    "xpath:idRelative",
                ],
                ["xpath=//div[3]/button", "xpath:position"],
                ["xpath=//button[contains(.,'Save HTML')]", "xpath:innerText"],
            ],
            "value": "",
        },
    ],
}
project_wrapper["tests"].append(header__archives)

with open(f"assets/project.side", "w") as fp:
    json.dump(project_wrapper, fp, indent=4)
