name: Build & Deploy Blog Posts
on:
  schedule:
    # blog posts go up once or twice a month, so once a day is plenty
    - cron: '20 13 * * *'
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write  # write is required to commit changes
  pages: write
  id-token: write
# NOTE deployment concurrency is handled in fragments.yml
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.commit.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 bleach feedparser

      - name: Create fragments directory
        run: mkdir -p fragments/blog

      - name: 🐞 python --version
        run: python --version

      - name: Build blog fragment from feed and blog page
        run: python .github/workflows/blog.py

      - name: Configure Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Commit changes
        id: commit
        run: echo "changed=false" >> $GITHUB_OUTPUT;
          git add fragments/blog;
          if ! git diff --staged --quiet;
          then
            git commit -m "update blog fragment";
            git push;
            echo "changed=true" >> $GITHUB_OUTPUT;
          fi;
          git log -1;
  deploy:
    needs: build
    if: needs.build.outputs.changes == 'true'
    permissions:
      pages: write
      id-token: write
    uses: ./.github/workflows/fragments.yml
