name: Compile Artifacts

on:
    workflow_call:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install plac
          curl --silent --show-error --location https://github.com/sass/dart-sass/releases/download/${{ vars.DART_SASS_VERSION }}/dart-sass-${{ vars.DART_SASS_VERSION }}-linux-x64.tar.gz | tar --extract --gzip
          mv dart-sass/sass /usr/local/bin
      - name: Create artifacts directory
        run: mkdir -p artifacts
      - name: Compile artifacts from changed files
        env:
          GROUPS: ${{ secrets.LIBGUIDES_GROUPS }}
        run: for f in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }});
          do
            python .github/workflows/compile.py "$f" --github-commit ${{ github.repository }}/commit/${{ github.sha }};
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compile-${{ github.sha }}
          path: artifacts
