name: Compile Artifacts

on:
  workflow_call:
    inputs:
      recompile:
        required: false
        type: string
    outputs:
      has_artifacts:
        description: "Whether any artifacts were compiled"
        value: ${{ jobs.compile.outputs.has_artifacts }}

jobs:
  compile:
    runs-on: ubuntu-latest
    outputs:
      has_artifacts: ${{ steps.check_artifacts.outputs.has_artifacts }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - name: Check changed files for SCSS
        id: compile_scss
        if: ${{ ! inputs.recompile }}
        run: |
          for f in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}); do
            if [[ "$f" == *".scss" ]]; then
              echo "SCSS=true" >> "$GITHUB_OUTPUT"
              break
            fi
          done
      - name: Check inputs for SCSS
        id: recompile_scss
        if: ${{ endsWith(inputs.recompile, '.scss') }}
        run: echo "SCSS=true" >> "$GITHUB_OUTPUT"
      - name: Conditionally install dart-sass
        if: steps.recompile_scss.outputs.SCSS == 'true' || steps.compile_scss.outputs.SCSS == 'true'
        run: |
          curl --silent --show-error --location https://github.com/sass/dart-sass/releases/download/${{ vars.DART_SASS_VERSION }}/dart-sass-${{ vars.DART_SASS_VERSION }}-linux-x64.tar.gz | tar --extract --gzip
          mv dart-sass/sass /usr/local/bin
      - name: Create artifacts directory
        run: mkdir -p artifacts
      - name: Compile artifacts from changed files
        if: ${{ ! inputs.recompile }}
        env:
          GROUPS: ${{ secrets.LIBGUIDES_GROUPS }}
        run: for f in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }});
          do
            python .github/workflows/compile.py "$f";
          done
      - name: Recompile artifact from input
        if: ${{ inputs.recompile }}
        env:
          GROUPS: ${{ secrets.LIBGUIDES_GROUPS }}
        run: python .github/workflows/compile.py ${{ inputs.recompile }};
      - name: Check for artifacts
        id: check_artifacts
        run: |
          if [ -n "$(ls -A artifacts)" ]; then
            echo "has_artifacts=true" >> $GITHUB_OUTPUT
          else
            echo "has_artifacts=false" >> $GITHUB_OUTPUT
          fi
      - name: Upload artifacts
        if: steps.check_artifacts.outputs.has_artifacts == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: compile-${{ github.sha }}
          path: artifacts
