name: Deploy Components
run-name: deploy ${{ github.event.head_commit.message || inputs.recompile }}

on:
  push:
    paths:
      - "**.scss"
      - "*.js"
      - "*.html"
      - "*.shtm"
  workflow_dispatch:
    inputs:
      recompile:
        description: 'Source file to recompile'
        required: true
        type: string
      debug:
        description: 'Record video for debugging'
        type: boolean
        default: false

jobs:
  compile:
    uses: ./.github/workflows/compile.yml
    with:
      recompile: ${{ inputs.recompile }}
    secrets: inherit
  deploy:
    runs-on: ubuntu-latest
    needs: compile
    container:
      image: mcr.microsoft.com/playwright/python:v${{ vars.PLAYWRIGHT_VERSION }}
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright==${{ vars.PLAYWRIGHT_VERSION }} pytest-playwright
      - uses: actions/download-artifact@v4
        with:
          name: compile-${{ github.sha }}
          path: artifacts
      - uses: step-security/wait-for-secrets@v1
        id: wait-for-secrets
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          secrets: |
            LIBAPPS_MFA_TOKEN: 
              name: 'LibApps MFA Token from email'
      - name: Deploy with pytest-playwright
        id: deploy
        env:
          USERNAME: ${{ secrets.ADMIN_USERNAME }}
          PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          LIBAPPS_MFA_TOKEN: ${{ steps.wait-for-secrets.outputs.LIBAPPS_MFA_TOKEN }}
          GROUPS: ${{ secrets.LIBGUIDES_GROUPS }}
        run: |
          if [ "${{ github.event.inputs.debug }}" = "true" ]; then
            pytest --slowmo 100 --video on --base-url ${{ secrets.ADMIN_BASE_URL }} -sv .github/workflows/deploy.py
          else
            pytest --base-url ${{ secrets.ADMIN_BASE_URL }} -sv .github/workflows/deploy.py
          fi
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: ${{ github.event.inputs.debug == 'true' }}
        with:
          name: deploy-${{ github.sha }}
          path: test-results/github-workflows-deploy-py-test-deploy-chromium
      - if: steps.deploy.outcome != 'success'
        run: exit 1
