name: Compile & Deploy to CMS
on:
  push:
    paths:
      - "**.scss"
      - "*.js"
      - "*.html"
      - "*.shtm"
  workflow_dispatch:
jobs:
  compile-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          playwright install firefox
          curl --silent --location https://github.com/sass/dart-sass/releases/download/1.53.0/dart-sass-1.53.0-linux-x64.tar.gz | tar --extract --gzip
          mv dart-sass/sass /usr/local/bin
      - name: Create artifacts directory
        run: mkdir -p artifacts
      - name: Compile artifacts from changed files
        # NOTE the LIBGUIDES_GROUPS secret must be single-quoted because it contains JSON
        run: for f in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }});
          do
            python workflow-compile.py "$f" '${{ secrets.LIBGUIDES_GROUPS }}' --github-commit ${{ github.repository }}/commit/${{ github.sha }};
          done
      - name: Deploy artifacts
        id: deploy
        # NOTE the LIBGUIDES_GROUPS secret must be single-quoted because it contains JSON
        run: |
          echo "STATUS=$(python workflow-deploy.py ${{ secrets.ADMIN_BASE_URL }} ${{ secrets.ADMIN_USERNAME }} ${{ secrets.ADMIN_PASSWORD }} '${{ secrets.LIBGUIDES_GROUPS }}')" >> $GITHUB_OUTPUT
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.workflow }} Artifacts-${{ github.run_number }}
          path: artifacts
      - name: Check deploy output
        if: ${{ steps.deploy.outputs.STATUS }}
        run: |
          echo ${{ steps.deploy.outputs.STATUS }}
          exit 1
